# LD2410 GPIO Configuration
binary_sensor:
   # LD2410 radar binary sensors
  - platform: gpio
    pin: 
      number: "${motion_gpio}"  # OUT pin of LD2410 connected here
      mode: INPUT_PULLUP
    name: "Motion Detected"
    id: motion_detected
    device_class: motion
    filters:
      - delayed_on: 10ms  # Optional: Debounce filter to avoid false triggers.
      - delayed_off: 10ms

  - platform: template
    name: "Occupancy Detected"
    device_class: occupancy
    lambda: |-
      return id(radar_has_target).state ||
             id(radar_has_moving_target).state ||
             id(radar_has_still_target).state ||
             id(motion_detected).state;

select:
    out_pin_level:
      name: out pin level
