# Define external packages that ESPHome will fetch at compile time.
# Add/change the dependencies you need.
# Delete any dependencies you don't need.
packages:
  project_configs: 
    url: https://github.com/AdmiralArgyle/guppi_occ
    files: [defaults/GUPPI.ST-OCC-GP-2410-AQI-DEFAULTS.yaml, shared-configs/boards/seeed_xiao_esp32s3.yaml, shared-configs/network/wifi.yaml, shared-configs/sensors/ld2410.yaml, shared-configs/sensors/bme680.yaml,shared-configs/sensors/bh1750.yaml]
    ref: main
    refresh: 60s

esphome:
  name: gopes-occupancy-xiao-s3-1
  friendly_name: "Luke's Office Gopes"
  comment: "${comment_text}"
  project: 
    name: "${project_name}"
    version: "${project_version}"

# Enable Home Assistant API
api:
  encryption:
    key: "SMMvzPVNVuzOUH5Yss9Ys6wSK10qsDHDhkYsiaDfOug="

