substitutions:
  name: dungeon-ble-tracker
  friendly_name: "Dungeon BLE Tracker"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging at DEBUG level for detailed output during development
logger:


# Enable Home Assistant API
api:
  encryption:
    key: "nPEAm2spqeEMTOr7zi7UMUrXrhE9DLnmmySuHxHym2U="

ota:
  - platform: esphome

# Enable Home Assistant API
wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_2_ssid
    password: !secret wifi_2_password
  - ssid: !secret wifi_3_ssid
    password: !secret wifi_3_password
  #power_save_mode: none
  output_power: 8.5dB

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name}"
    password: !secret fallback_ap_password

# Web server (optional, consider disabling in production)
#web_server:
#  port: 80

# Bluetooth Tracker & Proxy configuration
# Use esp-idf platform - not arduino
# Disable web server - don't use both at the same time
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

captive_portal:


################################################################################
# Basic diagnostic sensors
################################################################################

sensor:
  # Standard Diagnostic Sensors
  - platform: uptime
    name: "Device Uptime"
    id: sys_uptime
    update_interval: 60s
    entity_category: "diagnostic"
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"


################################################################################
# Text Sensors for Diagnostics and Derived Information
################################################################################
text_sensor:
  # Device IP Address
  - platform: wifi_info
    ip_address:
      name: "Device IP Address"
  # Firmware Version (optional)
  - platform: version
    name: "Firmware Version"

################################################################################
# Button Component to Restart the Device
################################################################################
button:
  - platform: restart
    icon: mdi:power-cycle
    name: "Reboot Sensor"
